# Generated by Django 4.2.2 on 2023-07-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_iemage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iemage',
            new_name='image',
        ),
    ]
