# Generated by Django 4.2.2 on 2023-07-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_iemage_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(verbose_name='rate'),
        ),
    ]
